# ---------------------------------------------------------------------------
# Unimplemented roadmap seams -- documented, not faked
# ---------------------------------------------------------------------------

class NeuralEffectiveAction:
    """
    TODO (not implemented): a graph neural network mapping gauge-link
    configurations to a learned scalar effective action S(U), trained
    so that its induced HMC force approximates (or improves on) the
    analytic Wilson action -- e.g. a message-passing GNN over the
    lattice graph with links as edge features. Needs a training
    dataset of configurations, a loss (e.g. matching force fields or
    matching observable expectation values), and a training loop.
    """

    def __init__(self, *args, **kwargs):
        raise NotImplementedError(
            "NeuralEffectiveAction is a documented roadmap seam, not an implementation. "
            "See the class docstring for what it would need."
        )


class FourierNeuralOperator:
    """
    TODO (not implemented): learn psi(t) -> psi(t + dt) directly in
    Fourier space (spectral convolution layers) as a fast surrogate
    for explicit lattice evolution. Needs training trajectories
    generated by the explicit solver above as supervision.
    """

    def __init__(self, *args, **kwargs):
        raise NotImplementedError(
            "FourierNeuralOperator is a documented roadmap seam, not an implementation."
        )


class _MLP(nn.Module):
    """Small fully-connected network; shared by the encoder and decoder."""

    def __init__(self, dims: List[int]):
        super().__init__()
        layers = []
        for i in range(len(dims) - 1):
            layers.append(nn.Linear(dims[i], dims[i + 1]))
            if i < len(dims) - 2:
                layers.append(nn.ReLU())
        self.net = nn.Sequential(*layers)

    def forward(self, x: "torch.Tensor") -> "torch.Tensor":
        return self.net(x)


class LearnedInformationGeometry:
    """
    A real Riemannian-geometry-on-a-learned-latent-space pipeline:

        psi (complex lattice field)
            -> flatten to a real vector
            -> encoder (MLP)      -> latent z
            -> decoder (MLP)      -> reconstruction of psi
        Gaussian observation model p(psi | z) = N(decoder(z), sigma^2 I)
            -> Fisher information metric  G(z) = (1/sigma^2) J(z)^T J(z)
               where J(z) = d(decoder)/dz, computed exactly via
               torch.func.jacrev (this is the standard pullback metric
               used in Riemannian-VAE / \"latent space oddity\"-style work)
            -> Christoffel symbols Gamma^k_{ij}(z) from G via jacrev
            -> Riemann tensor, Ricci tensor, and scalar curvature R(z)
               from the Christoffel symbols via central finite
               differences (a deliberate, documented choice: composing
               three nested jacrev calls through a matrix inverse is
               fragile and slow; a single layer of finite differences
               on top of an exact, autodiff-derived Jacobian is the
               standard practical compromise and is still \"real\"
               numerical differential geometry, not a proxy statistic).

    Training data comes for free from the physics already being
    computed: MetaFieldSimulationV2 feeds it the CG solutions x (from
    D x = b, solved against each HMC gauge background) as psi samples
    to autoencode -- no synthetic or external dataset required.

    Keep `latent_dim` small (3-4). The Riemann tensor has
    O(latent_dim^4) components and every curvature evaluation costs
    O(latent_dim^2) additional Jacobian evaluations, so this is meant
    for a compact learned summary of the field, not a high-dimensional
    embedding.
    """

    def __init__(self, lattice: "LatticeV2", config: "ConfigV2",
                 latent_dim: int = 3, hidden_dims: Tuple[int, ...] = (256, 64),
                 sigma: float = 1.0, lr: float = 1e-3):
        self.lattice = lattice
        self.config = config
        self.latent_dim = latent_dim
        self.sigma = sigma
        self.field_shape = lattice.shape + (config.spinor_dim, config.color_dim)
        self.input_dim = 2 * int(torch.tensor(self.field_shape).prod().item())

        enc_dims = [self.input_dim, *hidden_dims, latent_dim]
        dec_dims = [latent_dim, *reversed(hidden_dims), self.input_dim]
        self.encoder = _MLP(enc_dims).to(dtype=torch.float64)
        self.decoder = _MLP(dec_dims).to(dtype=torch.float64)

        params = list(self.encoder.parameters()) + list(self.decoder.parameters())
        self.optimizer = torch.optim.Adam(params, lr=lr)
        self.last_loss: Optional[float] = None

    def _flatten(self, psi: "torch.Tensor") -> "torch.Tensor":
        flat = psi.reshape(-1)
        return torch.cat([flat.real, flat.imag]).to(torch.float64)

    def _unflatten(self, vec: "torch.Tensor") -> "torch.Tensor":
        n = vec.shape[-1] // 2
        real, imag = vec[..., :n], vec[..., n:]
        flat_complex = (real + 1j * imag).to(self.config.dtype)
        return flat_complex.reshape(self.field_shape)

    def encode(self, psi: "torch.Tensor") -> "torch.Tensor":
        x = self._flatten(psi)
        return self.encoder(x)

    def decode(self, z: "torch.Tensor") -> "torch.Tensor":
        """Returns the flat real reconstruction vector (not unflattened)."""
        return self.decoder(z)

    def train_on_batch(self, psi_samples: List["torch.Tensor"]) -> float:
        """One Adam step of reconstruction (autoencoding) on a batch of
        psi field configurations. Returns the MSE loss."""
        x = torch.stack([self._flatten(p) for p in psi_samples])
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = torch.mean((x_hat - x) ** 2)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        self.last_loss = float(loss.item())
        return self.last_loss

    def fisher_metric(self, z: "torch.Tensor") -> "torch.Tensor":
        """
        G(z) = (1/sigma^2) J(z)^T J(z), the Fisher information metric
        of the Gaussian decoder model p(psi | z) = N(decoder(z), sigma^2 I),
        i.e. the pullback of the ambient Euclidean metric through the
        decoder. Uses torch.func.jacrev for an exact Jacobian.
        """
        J = torch.func.jacrev(self.decoder)(z)
        G = (J.transpose(-1, -2) @ J) / (self.sigma ** 2)
        return G

    def christoffel_symbols(self, z: "torch.Tensor", eps: float = 1e-4) -> "torch.Tensor":
        """
        Gamma^k_{ij} = 1/2 g^{kl} (d_i g_{jl} + d_j g_{il} - d_l g_{ij}),
        with d_i g_{jl}(z) obtained via torch.func.jacrev on the exact
        Fisher metric above. Returns a (dim, dim, dim) tensor indexed
        [k, i, j].
        """
        dim = self.latent_dim
        G = self.fisher_metric(z)
        eye = torch.eye(dim, dtype=G.dtype)
        G_inv = torch.linalg.inv(G + eps * eye)
        dG = torch.func.jacrev(self.fisher_metric)(z)
        term = (torch.einsum('jli->ijl', dG) + torch.einsum('ilj->ijl', dG) - dG)
        Gamma = 0.5 * torch.einsum('kl,ijl->kij', G_inv, term)
        return Gamma

    def curvature(self, z: "torch.Tensor", fd_eps: float = 1e-3) -> Dict[str, "torch.Tensor"]:
        """
        Full Riemann tensor, Ricci tensor, and scalar curvature at z.
        First derivatives (Christoffel symbols) are exact via autodiff;
        the one additional derivative needed for the Riemann tensor is
        taken by central finite differences on christoffel_symbols(z)
        (documented tradeoff -- see class docstring).
        """
        dim = self.latent_dim
        Gamma0 = self.christoffel_symbols(z)
        dGamma = torch.zeros(dim, dim, dim, dim, dtype=Gamma0.dtype)
        for m in range(dim):
            step = torch.zeros(dim, dtype=z.dtype)
            step[m] = fd_eps
            G_plus = self.christoffel_symbols(z + step)
            G_minus = self.christoffel_symbols(z - step)
            dGamma[:, :, :, m] = (G_plus - G_minus) / (2 * fd_eps)
        Riemann = torch.zeros(dim, dim, dim, dim, dtype=Gamma0.dtype)
        for l in range(dim):
            for i in range(dim):
                for j in range(dim):
                    for k in range(dim):
                        term1 = dGamma[l, j, k, i]
                        term2 = dGamma[l, i, k, j]
                        term3 = sum(Gamma0[l, i, m] * Gamma0[m, j, k] for m in range(dim))
                        term4 = sum(Gamma0[l, j, m] * Gamma0[m, i, k] for m in range(dim))
                        Riemann[l, i, j, k] = term1 - term2 + term3 - term4
        Ricci = torch.zeros(dim, dim, dtype=Gamma0.dtype)
        for j in range(dim):
            for k in range(dim):
                Ricci[j, k] = sum(Riemann[i, i, j, k] for i in range(dim))
        G = self.fisher_metric(z)
        eye = torch.eye(dim, dtype=G.dtype)
        G_inv = torch.linalg.inv(G + 1e-4 * eye)
        scalar_curvature = torch.einsum('jk,jk->', G_inv, Ricci)
        return {
            "metric": G,
            "christoffel": Gamma0,
            "riemann": Riemann,
            "ricci": Ricci,
            "scalar_curvature": scalar_curvature,
        }
